### ISSUE TITLE
Küsimustike järjekord 

### ISSUE THREAD

**Issue by merit26** [Richard-Aasa/Tarkvara-projekt#5]
Õpilase lehel on küsimustikud suvalises järjekorras

**Comment by janekos** [comment]
tegin korda pannes ng-repeati orderBy: 'title'

**Comment by merit26** [comment]
See ei tööta ikkagi nii. Richard vaatab ise.

**Comment by Richard-Aasa** [comment]
Tegin oma arust korda.
